imports:
    - { resource: alias.yml }

services:
    _defaults:
        autowire: true
        bind:
            $tables: '%tables%'
            $ext_images_path: '%core.root_path%ext/david63/announceonindex/adm/style/images'
        public: true

    david63.disableext.admin.controller:
        class: david63\disableext\controller\admin_controller

    david63.disableext.core.functions:
        class: david63\disableext\core\functions
